---
title: "Lab2"
author: "Leomart Crisostomo"
date: "3/22/2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
col_name = "Location"
col_type = "integer"
hcmv <- read.csv(file = "hcmv.data",
                 sep = ",",
                 header = TRUE,
                 na.string = "?",
                 col.names = col_name,
                 colClasses = col_type
                 )
locations = hcmv$Location
qqnorm(locations)
qqline(locations, col = 'red')

# Spacings of Palindromes
spacing = locations[-1] - locations[-296]

# exponential
range = locations[296] - locations[1]
rate_exp = 296/range
x = c(0:max(spacing))
plot(density(spacing), main = "Spacing Between Two Consecutive Palindromes", xlab = "Space")

hist(spacing, xlab = "Spacing", main = "Spacing between Two Consecutive Palindromes", prob = TRUE, col = 'cyan')
curve(dexp(x,rate_exp), col = 'darkviolet', lty = 2, add = TRUE)

# Sum of Consecutive Pair
sum_consecutive_pair = locations[-1] + locations[-296]
hist(sum_consecutive_pair, main= "Consecutive Pair of Palindromes", xlab = "Sum of Two Consecutive Pair of Palindromes", col = 'yellow')

# Sum of Three Consecutive Palindromes
grp = 3
sum_consecutive_triplets = sapply(1:(length(locations)-grp+1),function(x){sum(locations[x:(x+grp-1)])})
hist(sum_consecutive_triplets, xlab = "Sum of Three Consecutive Palindromes", main = "Three Consecutive Palindromes", col = 'purple')
```


```{r counts}
# Counts of Palindromes in intervals of 5000
# Use Chi Squared Test
library(knitr)
interval = 5000
max(hcmv) / 5000
bins = c()
for (i in 0:46){
  bins = c(bins, i * interval)
}
counts_hist = hist(locations, breaks = bins, main = "Palindrome Counts in Intervals of 5000", xlab = "Locations", col = 'deeppink3')
counts_palindromes = counts_hist$counts
palindrome_bin_count = c(0,2,3,4,5,6,7,8,9,20)

counts_palindromes_hist = hist(counts_palindromes, breaks = palindrome_bin_count , freq = TRUE, xlab = "Palindromes Count", col = 'darkslategray3')
#hist(counts_palindromes, breaks= palindrome_bin_count , freq = TRUE)
observed_num_interval = counts_palindromes_hist$counts
num_intervals = length(counts_palindromes)
rate = length(locations)/num_intervals

expected_0_1_2 = num_intervals * exp(-rate)*(1+rate+ rate^2/2)
expected_0_1_2
expected_num_interval = c(expected_0_1_2)
for (i in 3:9){
  expected_num_interval = c(expected_num_interval, num_intervals* exp(-rate) *(rate^i / factorial(i)))
}
expected_num_interval = c(expected_num_interval, num_intervals- sum(expected_num_interval))

# Table of Observed and Expected Number of Intervals
categories = c('0 1 or 2', 3, 4, 5, 6, 7, 8, 9, '10+')
column_names = c('Palindrome Count', 'Observed Number of Intervals', 'Expected Number of Intervals')
data_table = data.frame(categories, observed_num_interval ,round(expected_num_interval, 2))
kable(data_table, col.names = column_names)

barplot(observed_num_interval, col = rgb(0,0,1,.3), names.arg = categories, main = "Observed Vs Expected Number of Intervals", xlab = "Palindrome Count", legend = "Observed")
barplot(expected_num_interval,col = rgb(1,0,0,.3),legend = c("Expected"), add=TRUE, args.legend = list(x = "topleft"), ylab = "Number of Intervals")

# Perform Chi Squared Test
test_statistic = sum((expected_num_interval - observed_num_interval)^2 / expected_num_interval)
test_statistic
p_value = pchisq(test_statistic, df=9, lower.tail = FALSE)



```



```{r maximum hits}
# Maximum Number of Hits
scatter.smooth(counts_palindromes, col = 'blue', main = "Palindromes Count ", ylab = 'Number of Palindromes')
summary(counts_palindromes)
boxplot(counts_palindromes, main = "Palindromes Count", col = 'gold', ylab = 'Count')

test_statistic_max = max(counts_palindromes)
p_value_max = 0
for (i in 0:test_statistic_max){
  p_value_max = p_value_max + (rate^i *exp(-rate) / factorial(i))
}
p_value_max = 1- p_value_max
p_value_max
bins_interval = bins[1:length(bins)-1]
data_interval = data.frame(bins_interval, counts_palindromes)
kable(data_interval, col.names = c('Interval', 'Palindromes Count') )
max_segment = c(90000, 95000) 
```

